name: main

on: [push]

env:
  REGISTRY: docker-registry.spongepowered.org
  REGISTRY_USER: ${{ secrets.SPONGE_MAVEN_REPO_USER }}
  REGISTRY_PASSWORD: ${{ secrets.SPONGE_MAVEN_REPO_PASSWORD }}
  IMAGE_NAME: spongedocs

jobs:
  build-n-upload-translations:
    runs-on: ubuntu-latest

    outputs:
      branch: ${{ steps.variables.outputs.branch }}
      version: ${{ steps.variables.outputs.version }}
      versions: ${{ steps.variables.outputs.versions }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache pip dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Setup Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Python dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    - name: Test build
      run: sphinx-build -W -d build/doctrees source build/html
