name: main

on: [push]

jobs:
  build-upload:
    runs-on: ubuntu-latest

    outputs:
      branch: ${{ steps.variables.outputs.branch }}
      version: ${{ steps.variables.outputs.version }}
      versions: ${{ steps.variables.outputs.versions }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache pip dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Setup Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build
        run: sphinx-build -d build/doctrees source build/html

      # - name: Artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: Artifacts
      #     path: build

      # - name: setup jdk 8.0
      #   uses: actions/setup-java@v2
      #   with:
      #     distribution: adopt
      #     java-version: 8.0
      
      - name: Upload ftp
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_URL }}
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "./build/html"
          # remoteDir: "build/html/index.html"
          # options: "--delete --asci"

      # - name: Upload
      #   run: java -jar uploader.jar ./build/html ${{ secrets.FTP_URL }} ${{ secrets.FTP_USER }} ${{ secrets.FTP_PASSWORD }}