name: main

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      branch: ${{ steps.variables.outputs.branch }}
      version: ${{ steps.variables.outputs.version }}
      versions: ${{ steps.variables.outputs.versions }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache pip dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Setup Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Python dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

    - name: Test build
      run: sphinx-build -W -d build/doctrees source build/html

    - name: Build translation files
      run: sphinx-build -W -q -b gettext source build/locale

    - name: Upload files
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: build